name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      - name: Update version of 'kwz' package
        uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: git config --global user.name 'Gabriel Barker (CI)'
      - run: git config --global user.email 'gabrielbarker@gmail.com'
      - run: npm version patch
      - run: git push
