name: Publish package

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Publish 'kwz' package to npm
        uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
